### ISSUE TITLE
error

### ISSUE THREAD

**Issue by QianSu** [Phantomxm2021/ARMOD-FlutterAppDemo#2]
![image](https://user-images.githubusercontent.com/21114827/153819407-723fa495-3c76-49e2-819f-645ba028d2e9.png)

**Comment by QianSu** [comment]
![image](https://user-images.githubusercontent.com/21114827/153819512-3ba3d744-8412-4f4c-88e8-7ab02f8d2040.png)

**Comment by ChinmayaGit** [comment]
yes i have the same isuue as well any fix.
i just commented it but not helped it's just saying:-
e: D:\Software\Android studio\Flutter SDK\.pub-cache\hosted\pub.dartlang.org\flutter_armod_widget-0.0.5\android\src\main\kotlin\com\phantomsxr\armodplugin\FlutterARMODWidgetController.kt: (196, 5): 'onUnityPlayerUnloaded' overrides nothing

**Comment by Phantomxm2021** [comment]
> ![image](https://user-images.githubusercontent.com/21114827/153819512-3ba3d744-8412-4f4c-88e8-7ab02f8d2040.png)

Hi, Try pulling the git main branch again, we updated it to 2.0.0-p re.1 and it supports Flutter 3.0 now.

You must to upgrade your libs and framework.

A: **How to upgrade**?
Q: Go to [ARFramework repor]( https://github.com/Phantomxm2021/ARMOD-Framework/tree/Android-2.0.0-pre.1) and download it replace your old libs or framework.

**Comment by Phantomxm2021** [comment]
> yes i have the same isuue as well any fix. i just commented it but not helped it's just saying:- e: D:\Software\Android studio\Flutter SDK.pub-cache\hosted\pub.dartlang.org\flutter_armod_widget-0.0.5\android\src\main\kotlin\com\phantomsxr\armodplugin\FlutterARMODWidgetController.kt: (196, 5): 'onUnityPlayerUnloaded' overrides nothing

Hi, Try pulling the git main branch again, we updated it to 2.0.0-p re.1 and it supports Flutter 3.0 now.
